apiVersion: v1
kind: Pod
metadata:  
  name: configmap-pod 
spec:  
  containers:  
    - name: test-container  
      image: k8s.gcr.io/busybox  
      command: [ "/bin/sh", "-c", "env" ]  
      env:
      - name: KEY_NAME
        value: VALUE_NAME
      - name: KEY_NAME2
        valueFrom:
          configMapKeyRef:
            name: CONFIMAP_NAME
            key: CONFIGMAP_KEY_NAME
      - name: KEY_NAME3
        valueFrom:
          secretKeyRef:
            name: SECRET_NAME
            key: SECRET_KEY
      envFrom:  
      - configMapRef:  
          name: confimap-name 
      - secretRef:
          name: secret-name
      resources:
        limits:
          memory: "128Mi"
          cpu: 100m 
  restartPolicy: Never