apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: log-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 200Mi
  accessModes:
  - ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi