kubectl expose deployment redis --port=6379 --name messaging-service --namespace marketing

---

kubectl create deployment redis --image=redis:alpine --replicas=1

To expose the deployment using ClusterIP:
kubectl expose deployment redis --name=redis --port=6379 --target-port=6379


To create ingress rule:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-access
  namespace: default
spec:
  podSelector:
    matchLabels:
       app: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: redis
    ports:
     - protocol: TCP
       port: 6379

---

apiVersion: v1
kind: Pod
metadata:
  name: sega
spec:
  containers:
  - image: busybox
    name: tails
    command:
    - sleep
    - "3600"
  - image: nginx
    name: sonic
    env:
    - name: NGINX_PORT
      value: "8080"