apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: cont1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: cont2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
